// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lr.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PeerJoinRequest struct {
	PeerId               []byte   `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	LocalIp              string   `protobuf:"bytes,2,opt,name=local_ip,json=localIp" json:"local_ip,omitempty"`
	LocalPort            string   `protobuf:"bytes,3,opt,name=local_port,json=localPort" json:"local_port,omitempty"`
	Latitude             float32  `protobuf:"fixed32,4,opt,name=latitude" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,5,opt,name=longitude" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerJoinRequest) Reset()         { *m = PeerJoinRequest{} }
func (m *PeerJoinRequest) String() string { return proto.CompactTextString(m) }
func (*PeerJoinRequest) ProtoMessage()    {}
func (*PeerJoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lr_61c67d4160214c2e, []int{0}
}
func (m *PeerJoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerJoinRequest.Unmarshal(m, b)
}
func (m *PeerJoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerJoinRequest.Marshal(b, m, deterministic)
}
func (dst *PeerJoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerJoinRequest.Merge(dst, src)
}
func (m *PeerJoinRequest) XXX_Size() int {
	return xxx_messageInfo_PeerJoinRequest.Size(m)
}
func (m *PeerJoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerJoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeerJoinRequest proto.InternalMessageInfo

func (m *PeerJoinRequest) GetPeerId() []byte {
	if m != nil {
		return m.PeerId
	}
	return nil
}

func (m *PeerJoinRequest) GetLocalIp() string {
	if m != nil {
		return m.LocalIp
	}
	return ""
}

func (m *PeerJoinRequest) GetLocalPort() string {
	if m != nil {
		return m.LocalPort
	}
	return ""
}

func (m *PeerJoinRequest) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *PeerJoinRequest) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type PeerJoinResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerJoinResponse) Reset()         { *m = PeerJoinResponse{} }
func (m *PeerJoinResponse) String() string { return proto.CompactTextString(m) }
func (*PeerJoinResponse) ProtoMessage()    {}
func (*PeerJoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_lr_61c67d4160214c2e, []int{1}
}
func (m *PeerJoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerJoinResponse.Unmarshal(m, b)
}
func (m *PeerJoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerJoinResponse.Marshal(b, m, deterministic)
}
func (dst *PeerJoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerJoinResponse.Merge(dst, src)
}
func (m *PeerJoinResponse) XXX_Size() int {
	return xxx_messageInfo_PeerJoinResponse.Size(m)
}
func (m *PeerJoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerJoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PeerJoinResponse proto.InternalMessageInfo

func (m *PeerJoinResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type PeerEntry struct {
	PeerId               []byte   `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	LocalIp              string   `protobuf:"bytes,2,opt,name=local_ip,json=localIp" json:"local_ip,omitempty"`
	LocalPort            string   `protobuf:"bytes,3,opt,name=local_port,json=localPort" json:"local_port,omitempty"`
	Latitude             float32  `protobuf:"fixed32,4,opt,name=latitude" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,5,opt,name=longitude" json:"longitude,omitempty"`
	IsRemote             bool     `protobuf:"varint,6,opt,name=is_remote,json=isRemote" json:"is_remote,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerEntry) Reset()         { *m = PeerEntry{} }
func (m *PeerEntry) String() string { return proto.CompactTextString(m) }
func (*PeerEntry) ProtoMessage()    {}
func (*PeerEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_lr_61c67d4160214c2e, []int{2}
}
func (m *PeerEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerEntry.Unmarshal(m, b)
}
func (m *PeerEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerEntry.Marshal(b, m, deterministic)
}
func (dst *PeerEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerEntry.Merge(dst, src)
}
func (m *PeerEntry) XXX_Size() int {
	return xxx_messageInfo_PeerEntry.Size(m)
}
func (m *PeerEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PeerEntry proto.InternalMessageInfo

func (m *PeerEntry) GetPeerId() []byte {
	if m != nil {
		return m.PeerId
	}
	return nil
}

func (m *PeerEntry) GetLocalIp() string {
	if m != nil {
		return m.LocalIp
	}
	return ""
}

func (m *PeerEntry) GetLocalPort() string {
	if m != nil {
		return m.LocalPort
	}
	return ""
}

func (m *PeerEntry) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *PeerEntry) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *PeerEntry) GetIsRemote() bool {
	if m != nil {
		return m.IsRemote
	}
	return false
}

func init() {
	proto.RegisterType((*PeerJoinRequest)(nil), "proto.PeerJoinRequest")
	proto.RegisterType((*PeerJoinResponse)(nil), "proto.PeerJoinResponse")
	proto.RegisterType((*PeerEntry)(nil), "proto.PeerEntry")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LRClient is the client API for LR service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LRClient interface {
	Heartbeat(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	PeerJoinRPC(ctx context.Context, in *PeerJoinRequest, opts ...grpc.CallOption) (*PeerJoinResponse, error)
}

type lRClient struct {
	cc *grpc.ClientConn
}

func NewLRClient(cc *grpc.ClientConn) LRClient {
	return &lRClient{cc}
}

func (c *lRClient) Heartbeat(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.LR/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lRClient) PeerJoinRPC(ctx context.Context, in *PeerJoinRequest, opts ...grpc.CallOption) (*PeerJoinResponse, error) {
	out := new(PeerJoinResponse)
	err := c.cc.Invoke(ctx, "/proto.LR/PeerJoinRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LR service

type LRServer interface {
	Heartbeat(context.Context, *Empty) (*Empty, error)
	PeerJoinRPC(context.Context, *PeerJoinRequest) (*PeerJoinResponse, error)
}

func RegisterLRServer(s *grpc.Server, srv LRServer) {
	s.RegisterService(&_LR_serviceDesc, srv)
}

func _LR_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LRServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LR/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LRServer).Heartbeat(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LR_PeerJoinRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LRServer).PeerJoinRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LR/PeerJoinRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LRServer).PeerJoinRPC(ctx, req.(*PeerJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LR_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.LR",
	HandlerType: (*LRServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _LR_Heartbeat_Handler,
		},
		{
			MethodName: "PeerJoinRPC",
			Handler:    _LR_PeerJoinRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lr.proto",
}

func init() { proto.RegisterFile("lr.proto", fileDescriptor_lr_61c67d4160214c2e) }

var fileDescriptor_lr_61c67d4160214c2e = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x91, 0xb1, 0x4e, 0xf3, 0x30,
	0x14, 0x85, 0xe5, 0xfe, 0x7f, 0xdb, 0xf8, 0xb6, 0x12, 0xe8, 0x0e, 0xd4, 0x04, 0x90, 0xa2, 0x2c,
	0x64, 0x40, 0x1d, 0x60, 0x67, 0x41, 0x95, 0x28, 0x62, 0x88, 0xfc, 0x02, 0x51, 0x9a, 0x5c, 0x21,
	0x4b, 0x49, 0x6c, 0x6c, 0x67, 0xe8, 0xcb, 0xf0, 0x16, 0xbc, 0x1f, 0x8a, 0x03, 0xad, 0x80, 0x17,
	0x60, 0x8a, 0xbe, 0xf3, 0x65, 0x38, 0xbe, 0x07, 0xa2, 0xc6, 0xae, 0x8d, 0xd5, 0x5e, 0xe3, 0x34,
	0x7c, 0xe2, 0x05, 0xb5, 0xc6, 0xef, 0xc7, 0x2c, 0x7d, 0x63, 0x70, 0x92, 0x13, 0xd9, 0x27, 0xad,
	0x3a, 0x49, 0xaf, 0x3d, 0x39, 0x8f, 0x2b, 0x98, 0x1b, 0x22, 0x5b, 0xa8, 0x5a, 0xb0, 0x84, 0x65,
	0x4b, 0x39, 0x1b, 0x70, 0x5b, 0xe3, 0x39, 0x44, 0x8d, 0xae, 0xca, 0xa6, 0x50, 0x46, 0x4c, 0x12,
	0x96, 0x71, 0x39, 0x0f, 0xbc, 0x35, 0x78, 0x05, 0x30, 0x2a, 0xa3, 0xad, 0x17, 0xff, 0x82, 0xe4,
	0x21, 0xc9, 0xb5, 0xf5, 0x18, 0x43, 0xd4, 0x94, 0x5e, 0xf9, 0xbe, 0x26, 0xf1, 0x3f, 0x61, 0xd9,
	0x44, 0x1e, 0x18, 0x2f, 0x81, 0x37, 0xba, 0x7b, 0x19, 0xe5, 0x34, 0xc8, 0x63, 0x90, 0xde, 0xc0,
	0xe9, 0xb1, 0x9f, 0x33, 0xba, 0x73, 0x84, 0x02, 0xe6, 0xae, 0xaf, 0x2a, 0x72, 0x2e, 0x14, 0x8c,
	0xe4, 0x17, 0xa6, 0xef, 0x0c, 0xf8, 0xf0, 0xfb, 0xa6, 0xf3, 0x76, 0xff, 0xa7, 0x1e, 0x82, 0x17,
	0xc0, 0x95, 0x2b, 0x2c, 0xb5, 0xda, 0x93, 0x98, 0x85, 0xda, 0x91, 0x72, 0x32, 0xf0, 0x6d, 0x0b,
	0x93, 0x67, 0x89, 0xd7, 0xc0, 0x1f, 0xa9, 0xb4, 0x7e, 0x47, 0xa5, 0xc7, 0xe5, 0xb8, 0xd0, 0x7a,
	0x33, 0xac, 0x15, 0x7f, 0x23, 0xbc, 0x87, 0xc5, 0xe1, 0x28, 0xf9, 0x03, 0x9e, 0x7d, 0xca, 0x1f,
	0x43, 0xc6, 0xab, 0x5f, 0xf9, 0x78, 0xc0, 0xdd, 0x2c, 0xe4, 0x77, 0x1f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xa7, 0xfc, 0x0c, 0x87, 0x1c, 0x02, 0x00, 0x00,
}
