// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LookUpPeerRequest struct {
	Latitude             float32  `protobuf:"fixed32,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,2,opt,name=longitude" json:"longitude,omitempty"`
	Distance             float32  `protobuf:"fixed32,3,opt,name=distance" json:"distance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookUpPeerRequest) Reset()         { *m = LookUpPeerRequest{} }
func (m *LookUpPeerRequest) String() string { return proto.CompactTextString(m) }
func (*LookUpPeerRequest) ProtoMessage()    {}
func (*LookUpPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_1a39e56e14a9f64a, []int{0}
}
func (m *LookUpPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookUpPeerRequest.Unmarshal(m, b)
}
func (m *LookUpPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookUpPeerRequest.Marshal(b, m, deterministic)
}
func (dst *LookUpPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookUpPeerRequest.Merge(dst, src)
}
func (m *LookUpPeerRequest) XXX_Size() int {
	return xxx_messageInfo_LookUpPeerRequest.Size(m)
}
func (m *LookUpPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookUpPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookUpPeerRequest proto.InternalMessageInfo

func (m *LookUpPeerRequest) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *LookUpPeerRequest) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *LookUpPeerRequest) GetDistance() float32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

type LookUpPeerResponse struct {
	Entries              []*PeerEntry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LookUpPeerResponse) Reset()         { *m = LookUpPeerResponse{} }
func (m *LookUpPeerResponse) String() string { return proto.CompactTextString(m) }
func (*LookUpPeerResponse) ProtoMessage()    {}
func (*LookUpPeerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_request_1a39e56e14a9f64a, []int{1}
}
func (m *LookUpPeerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookUpPeerResponse.Unmarshal(m, b)
}
func (m *LookUpPeerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookUpPeerResponse.Marshal(b, m, deterministic)
}
func (dst *LookUpPeerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookUpPeerResponse.Merge(dst, src)
}
func (m *LookUpPeerResponse) XXX_Size() int {
	return xxx_messageInfo_LookUpPeerResponse.Size(m)
}
func (m *LookUpPeerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LookUpPeerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LookUpPeerResponse proto.InternalMessageInfo

func (m *LookUpPeerResponse) GetEntries() []*PeerEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func init() {
	proto.RegisterType((*LookUpPeerRequest)(nil), "proto.LookUpPeerRequest")
	proto.RegisterType((*LookUpPeerResponse)(nil), "proto.LookUpPeerResponse")
}

func init() { proto.RegisterFile("request.proto", fileDescriptor_request_1a39e56e14a9f64a) }

var fileDescriptor_request_1a39e56e14a9f64a = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0xdc, 0xa9,
	0x79, 0x25, 0x45, 0x95, 0x10, 0x31, 0xa5, 0x4c, 0x2e, 0x41, 0x9f, 0xfc, 0xfc, 0xec, 0xd0, 0x82,
	0x80, 0xd4, 0xd4, 0xa2, 0x20, 0x88, 0x72, 0x21, 0x29, 0x2e, 0x8e, 0x9c, 0xc4, 0x92, 0xcc, 0x92,
	0xd2, 0x94, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xa6, 0x20, 0x38, 0x5f, 0x48, 0x86, 0x8b, 0x33,
	0x27, 0x3f, 0x2f, 0x1d, 0x22, 0xc9, 0x04, 0x96, 0x44, 0x08, 0x80, 0x74, 0xa6, 0x64, 0x16, 0x97,
	0x24, 0xe6, 0x25, 0xa7, 0x4a, 0x30, 0x43, 0x74, 0xc2, 0xf8, 0x4a, 0x0e, 0x5c, 0x42, 0xc8, 0x56,
	0x15, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x69, 0x71, 0xb1, 0x83, 0xdc, 0x93, 0x99, 0x5a, 0x2c,
	0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0x24, 0x00, 0x71, 0x99, 0x1e, 0x48, 0x95, 0x2b, 0xc8, 0xa5,
	0x41, 0x30, 0x05, 0x49, 0x6c, 0x60, 0x19, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x44, 0x8b,
	0x93, 0x3b, 0xd8, 0x00, 0x00, 0x00,
}
