// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tablet.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LRJoinRequest struct {
	GlobalPort           string   `protobuf:"bytes,2,opt,name=global_port,json=globalPort" json:"global_port,omitempty"`
	Latitude             float32  `protobuf:"fixed32,3,opt,name=latitude" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,4,opt,name=longitude" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LRJoinRequest) Reset()         { *m = LRJoinRequest{} }
func (m *LRJoinRequest) String() string { return proto.CompactTextString(m) }
func (*LRJoinRequest) ProtoMessage()    {}
func (*LRJoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tablet_0b2b0ed25e3efdac, []int{0}
}
func (m *LRJoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LRJoinRequest.Unmarshal(m, b)
}
func (m *LRJoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LRJoinRequest.Marshal(b, m, deterministic)
}
func (dst *LRJoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LRJoinRequest.Merge(dst, src)
}
func (m *LRJoinRequest) XXX_Size() int {
	return xxx_messageInfo_LRJoinRequest.Size(m)
}
func (m *LRJoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LRJoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LRJoinRequest proto.InternalMessageInfo

func (m *LRJoinRequest) GetGlobalPort() string {
	if m != nil {
		return m.GlobalPort
	}
	return ""
}

func (m *LRJoinRequest) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *LRJoinRequest) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type LookUpRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookUpRequest) Reset()         { *m = LookUpRequest{} }
func (m *LookUpRequest) String() string { return proto.CompactTextString(m) }
func (*LookUpRequest) ProtoMessage()    {}
func (*LookUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tablet_0b2b0ed25e3efdac, []int{1}
}
func (m *LookUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookUpRequest.Unmarshal(m, b)
}
func (m *LookUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookUpRequest.Marshal(b, m, deterministic)
}
func (dst *LookUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookUpRequest.Merge(dst, src)
}
func (m *LookUpRequest) XXX_Size() int {
	return xxx_messageInfo_LookUpRequest.Size(m)
}
func (m *LookUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookUpRequest proto.InternalMessageInfo

func (m *LookUpRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LREntry struct {
	Id                   uint32   `protobuf:"varint,7,opt,name=id" json:"id,omitempty"`
	GlobalIp             string   `protobuf:"bytes,1,opt,name=global_ip,json=globalIp" json:"global_ip,omitempty"`
	GlobalPort           string   `protobuf:"bytes,2,opt,name=global_port,json=globalPort" json:"global_port,omitempty"`
	Latitude             float32  `protobuf:"fixed32,3,opt,name=latitude" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,4,opt,name=longitude" json:"longitude,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,6,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LREntry) Reset()         { *m = LREntry{} }
func (m *LREntry) String() string { return proto.CompactTextString(m) }
func (*LREntry) ProtoMessage()    {}
func (*LREntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_tablet_0b2b0ed25e3efdac, []int{2}
}
func (m *LREntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LREntry.Unmarshal(m, b)
}
func (m *LREntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LREntry.Marshal(b, m, deterministic)
}
func (dst *LREntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LREntry.Merge(dst, src)
}
func (m *LREntry) XXX_Size() int {
	return xxx_messageInfo_LREntry.Size(m)
}
func (m *LREntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LREntry.DiscardUnknown(m)
}

var xxx_messageInfo_LREntry proto.InternalMessageInfo

func (m *LREntry) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LREntry) GetGlobalIp() string {
	if m != nil {
		return m.GlobalIp
	}
	return ""
}

func (m *LREntry) GetGlobalPort() string {
	if m != nil {
		return m.GlobalPort
	}
	return ""
}

func (m *LREntry) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *LREntry) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *LREntry) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *LREntry) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type LREntries struct {
	Entries              []*LREntry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LREntries) Reset()         { *m = LREntries{} }
func (m *LREntries) String() string { return proto.CompactTextString(m) }
func (*LREntries) ProtoMessage()    {}
func (*LREntries) Descriptor() ([]byte, []int) {
	return fileDescriptor_tablet_0b2b0ed25e3efdac, []int{3}
}
func (m *LREntries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LREntries.Unmarshal(m, b)
}
func (m *LREntries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LREntries.Marshal(b, m, deterministic)
}
func (dst *LREntries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LREntries.Merge(dst, src)
}
func (m *LREntries) XXX_Size() int {
	return xxx_messageInfo_LREntries.Size(m)
}
func (m *LREntries) XXX_DiscardUnknown() {
	xxx_messageInfo_LREntries.DiscardUnknown(m)
}

var xxx_messageInfo_LREntries proto.InternalMessageInfo

func (m *LREntries) GetEntries() []*LREntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func init() {
	proto.RegisterType((*LRJoinRequest)(nil), "proto.LRJoinRequest")
	proto.RegisterType((*LookUpRequest)(nil), "proto.LookUpRequest")
	proto.RegisterType((*LREntry)(nil), "proto.LREntry")
	proto.RegisterType((*LREntries)(nil), "proto.LREntries")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TabletClient is the client API for Tablet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TabletClient interface {
	LRJoinRPC(ctx context.Context, in *LRJoinRequest, opts ...grpc.CallOption) (*LREntry, error)
	LookUpRPC(ctx context.Context, in *LookUpRequest, opts ...grpc.CallOption) (*LREntry, error)
}

type tabletClient struct {
	cc *grpc.ClientConn
}

func NewTabletClient(cc *grpc.ClientConn) TabletClient {
	return &tabletClient{cc}
}

func (c *tabletClient) LRJoinRPC(ctx context.Context, in *LRJoinRequest, opts ...grpc.CallOption) (*LREntry, error) {
	out := new(LREntry)
	err := c.cc.Invoke(ctx, "/proto.Tablet/LRJoinRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tabletClient) LookUpRPC(ctx context.Context, in *LookUpRequest, opts ...grpc.CallOption) (*LREntry, error) {
	out := new(LREntry)
	err := c.cc.Invoke(ctx, "/proto.Tablet/LookUpRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tablet service

type TabletServer interface {
	LRJoinRPC(context.Context, *LRJoinRequest) (*LREntry, error)
	LookUpRPC(context.Context, *LookUpRequest) (*LREntry, error)
}

func RegisterTabletServer(s *grpc.Server, srv TabletServer) {
	s.RegisterService(&_Tablet_serviceDesc, srv)
}

func _Tablet_LRJoinRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LRJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TabletServer).LRJoinRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Tablet/LRJoinRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TabletServer).LRJoinRPC(ctx, req.(*LRJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tablet_LookUpRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TabletServer).LookUpRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Tablet/LookUpRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TabletServer).LookUpRPC(ctx, req.(*LookUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tablet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Tablet",
	HandlerType: (*TabletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LRJoinRPC",
			Handler:    _Tablet_LRJoinRPC_Handler,
		},
		{
			MethodName: "LookUpRPC",
			Handler:    _Tablet_LookUpRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tablet.proto",
}

func init() { proto.RegisterFile("tablet.proto", fileDescriptor_tablet_0b2b0ed25e3efdac) }

var fileDescriptor_tablet_0b2b0ed25e3efdac = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x91, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x86, 0xb3, 0x60, 0xa1, 0x3b, 0x95, 0x1e, 0x36, 0x1e, 0x48, 0xd5, 0x94, 0x70, 0xda, 0x53,
	0x13, 0x6b, 0x7c, 0x80, 0xc6, 0x78, 0xd0, 0x70, 0x68, 0x36, 0x7a, 0x6e, 0x40, 0x36, 0xcd, 0x2a,
	0x61, 0x57, 0x3a, 0x1c, 0x7c, 0x4a, 0x5f, 0xc9, 0x74, 0x77, 0xa9, 0xa4, 0x77, 0x4f, 0x30, 0xff,
	0xc7, 0x3f, 0xcc, 0xcc, 0x0f, 0x97, 0x58, 0x56, 0x8d, 0xc4, 0x95, 0xe9, 0x34, 0x6a, 0x36, 0xb1,
	0x8f, 0xfc, 0x03, 0x92, 0x42, 0xbc, 0x68, 0xd5, 0x0a, 0xf9, 0xd5, 0xcb, 0x03, 0xb2, 0x25, 0xcc,
	0xf6, 0x8d, 0xae, 0xca, 0x66, 0x67, 0x74, 0x87, 0x69, 0x90, 0x11, 0x4e, 0x05, 0x38, 0x69, 0xab,
	0x3b, 0x64, 0x0b, 0x98, 0x36, 0x25, 0x2a, 0xec, 0x6b, 0x99, 0x86, 0x19, 0xe1, 0x81, 0x38, 0xd5,
	0xec, 0x06, 0x68, 0xa3, 0xdb, 0xbd, 0x83, 0x17, 0x16, 0xfe, 0x09, 0xf9, 0x12, 0x92, 0x42, 0xeb,
	0xcf, 0x37, 0x33, 0xfc, 0x6b, 0x0e, 0x81, 0xaa, 0x53, 0x92, 0x11, 0x9e, 0x88, 0x40, 0xd5, 0xf9,
	0x0f, 0x81, 0xb8, 0x10, 0x4f, 0x2d, 0x76, 0xdf, 0x9e, 0xc5, 0x03, 0x63, 0xd7, 0x40, 0xfd, 0x5c,
	0xca, 0x58, 0x0b, 0x15, 0x53, 0x27, 0x3c, 0x9b, 0x7f, 0x1c, 0x9a, 0xdd, 0x02, 0xbc, 0x77, 0xb2,
	0x44, 0x59, 0xef, 0x4a, 0x4c, 0x27, 0x19, 0xe1, 0xa1, 0xa0, 0x5e, 0xd9, 0xe0, 0x11, 0xf7, 0xa6,
	0x1e, 0x70, 0xe4, 0xb0, 0x57, 0x36, 0x98, 0x3f, 0x00, 0x75, 0x0b, 0x29, 0x79, 0x60, 0x1c, 0x62,
	0xe9, 0x5e, 0x53, 0x92, 0x85, 0x7c, 0xb6, 0x9e, 0xbb, 0x2c, 0x56, 0x7e, 0x67, 0x31, 0xe0, 0x75,
	0x0b, 0xd1, 0xab, 0x0d, 0x8b, 0xdd, 0x1d, 0x1b, 0xd8, 0x7c, 0xb6, 0x8f, 0xec, 0xea, 0xf4, 0xfd,
	0x28, 0xb1, 0xc5, 0x59, 0x17, 0x6b, 0x71, 0x67, 0x1e, 0x5b, 0xc6, 0x87, 0x3f, 0xb7, 0x54, 0x91,
	0x2d, 0xef, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x46, 0xda, 0xba, 0x23, 0x02, 0x00, 0x00,
}
