// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tablet.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LRJoinRequest struct {
	GlobalIp             string   `protobuf:"bytes,1,opt,name=global_ip,json=globalIp" json:"global_ip,omitempty"`
	GlobalPort           string   `protobuf:"bytes,2,opt,name=global_port,json=globalPort" json:"global_port,omitempty"`
	Latitude             float32  `protobuf:"fixed32,3,opt,name=latitude" json:"latitude,omitempty"`
	Longtitude           float32  `protobuf:"fixed32,4,opt,name=longtitude" json:"longtitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LRJoinRequest) Reset()         { *m = LRJoinRequest{} }
func (m *LRJoinRequest) String() string { return proto.CompactTextString(m) }
func (*LRJoinRequest) ProtoMessage()    {}
func (*LRJoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tablet_e53f6c4798b8e384, []int{0}
}
func (m *LRJoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LRJoinRequest.Unmarshal(m, b)
}
func (m *LRJoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LRJoinRequest.Marshal(b, m, deterministic)
}
func (dst *LRJoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LRJoinRequest.Merge(dst, src)
}
func (m *LRJoinRequest) XXX_Size() int {
	return xxx_messageInfo_LRJoinRequest.Size(m)
}
func (m *LRJoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LRJoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LRJoinRequest proto.InternalMessageInfo

func (m *LRJoinRequest) GetGlobalIp() string {
	if m != nil {
		return m.GlobalIp
	}
	return ""
}

func (m *LRJoinRequest) GetGlobalPort() string {
	if m != nil {
		return m.GlobalPort
	}
	return ""
}

func (m *LRJoinRequest) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *LRJoinRequest) GetLongtitude() float32 {
	if m != nil {
		return m.Longtitude
	}
	return 0
}

type LRJoinResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LRJoinResponse) Reset()         { *m = LRJoinResponse{} }
func (m *LRJoinResponse) String() string { return proto.CompactTextString(m) }
func (*LRJoinResponse) ProtoMessage()    {}
func (*LRJoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_tablet_e53f6c4798b8e384, []int{1}
}
func (m *LRJoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LRJoinResponse.Unmarshal(m, b)
}
func (m *LRJoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LRJoinResponse.Marshal(b, m, deterministic)
}
func (dst *LRJoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LRJoinResponse.Merge(dst, src)
}
func (m *LRJoinResponse) XXX_Size() int {
	return xxx_messageInfo_LRJoinResponse.Size(m)
}
func (m *LRJoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LRJoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LRJoinResponse proto.InternalMessageInfo

func (m *LRJoinResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type LREntry struct {
	GlobalIp             string   `protobuf:"bytes,1,opt,name=global_ip,json=globalIp" json:"global_ip,omitempty"`
	GlobalPort           string   `protobuf:"bytes,2,opt,name=global_port,json=globalPort" json:"global_port,omitempty"`
	Latitude             float32  `protobuf:"fixed32,3,opt,name=latitude" json:"latitude,omitempty"`
	Longtitude           float32  `protobuf:"fixed32,4,opt,name=longtitude" json:"longtitude,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,6,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LREntry) Reset()         { *m = LREntry{} }
func (m *LREntry) String() string { return proto.CompactTextString(m) }
func (*LREntry) ProtoMessage()    {}
func (*LREntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_tablet_e53f6c4798b8e384, []int{2}
}
func (m *LREntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LREntry.Unmarshal(m, b)
}
func (m *LREntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LREntry.Marshal(b, m, deterministic)
}
func (dst *LREntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LREntry.Merge(dst, src)
}
func (m *LREntry) XXX_Size() int {
	return xxx_messageInfo_LREntry.Size(m)
}
func (m *LREntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LREntry.DiscardUnknown(m)
}

var xxx_messageInfo_LREntry proto.InternalMessageInfo

func (m *LREntry) GetGlobalIp() string {
	if m != nil {
		return m.GlobalIp
	}
	return ""
}

func (m *LREntry) GetGlobalPort() string {
	if m != nil {
		return m.GlobalPort
	}
	return ""
}

func (m *LREntry) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *LREntry) GetLongtitude() float32 {
	if m != nil {
		return m.Longtitude
	}
	return 0
}

func (m *LREntry) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *LREntry) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type LREntries struct {
	Entries              []*LREntry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *LREntries) Reset()         { *m = LREntries{} }
func (m *LREntries) String() string { return proto.CompactTextString(m) }
func (*LREntries) ProtoMessage()    {}
func (*LREntries) Descriptor() ([]byte, []int) {
	return fileDescriptor_tablet_e53f6c4798b8e384, []int{3}
}
func (m *LREntries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LREntries.Unmarshal(m, b)
}
func (m *LREntries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LREntries.Marshal(b, m, deterministic)
}
func (dst *LREntries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LREntries.Merge(dst, src)
}
func (m *LREntries) XXX_Size() int {
	return xxx_messageInfo_LREntries.Size(m)
}
func (m *LREntries) XXX_DiscardUnknown() {
	xxx_messageInfo_LREntries.DiscardUnknown(m)
}

var xxx_messageInfo_LREntries proto.InternalMessageInfo

func (m *LREntries) GetEntries() []*LREntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func init() {
	proto.RegisterType((*LRJoinRequest)(nil), "proto.LRJoinRequest")
	proto.RegisterType((*LRJoinResponse)(nil), "proto.LRJoinResponse")
	proto.RegisterType((*LREntry)(nil), "proto.LREntry")
	proto.RegisterType((*LREntries)(nil), "proto.LREntries")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TabletClient is the client API for Tablet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TabletClient interface {
	LRJoinRPC(ctx context.Context, in *LRJoinRequest, opts ...grpc.CallOption) (*LRJoinResponse, error)
}

type tabletClient struct {
	cc *grpc.ClientConn
}

func NewTabletClient(cc *grpc.ClientConn) TabletClient {
	return &tabletClient{cc}
}

func (c *tabletClient) LRJoinRPC(ctx context.Context, in *LRJoinRequest, opts ...grpc.CallOption) (*LRJoinResponse, error) {
	out := new(LRJoinResponse)
	err := c.cc.Invoke(ctx, "/proto.Tablet/LRJoinRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tablet service

type TabletServer interface {
	LRJoinRPC(context.Context, *LRJoinRequest) (*LRJoinResponse, error)
}

func RegisterTabletServer(s *grpc.Server, srv TabletServer) {
	s.RegisterService(&_Tablet_serviceDesc, srv)
}

func _Tablet_LRJoinRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LRJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TabletServer).LRJoinRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Tablet/LRJoinRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TabletServer).LRJoinRPC(ctx, req.(*LRJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tablet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Tablet",
	HandlerType: (*TabletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LRJoinRPC",
			Handler:    _Tablet_LRJoinRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tablet.proto",
}

func init() { proto.RegisterFile("tablet.proto", fileDescriptor_tablet_e53f6c4798b8e384) }

var fileDescriptor_tablet_e53f6c4798b8e384 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x91, 0xcd, 0x4a, 0x03, 0x31,
	0x10, 0xc7, 0x49, 0xd7, 0xee, 0xc7, 0x54, 0x7b, 0x08, 0x0a, 0xa1, 0xa2, 0x2e, 0x7b, 0x5a, 0x3c,
	0xf4, 0x50, 0x11, 0xbc, 0x56, 0xf1, 0xa0, 0xf4, 0x50, 0x82, 0xf7, 0xb2, 0x1f, 0x43, 0x59, 0x58,
	0x36, 0x71, 0x33, 0x7b, 0xf0, 0x11, 0x7c, 0x2c, 0xdf, 0x4c, 0x9a, 0x64, 0x4b, 0xf1, 0x05, 0x3c,
	0x25, 0xf3, 0xfb, 0x85, 0x30, 0x33, 0x7f, 0x38, 0xa7, 0xa2, 0x6c, 0x91, 0x96, 0xba, 0x57, 0xa4,
	0xf8, 0xd4, 0x1e, 0xd9, 0x37, 0x83, 0x8b, 0x8d, 0x7c, 0x57, 0x4d, 0x27, 0xf1, 0x73, 0x40, 0x43,
	0xfc, 0x1a, 0x92, 0x7d, 0xab, 0xca, 0xa2, 0xdd, 0x35, 0x5a, 0xb0, 0x94, 0xe5, 0x89, 0x8c, 0x1d,
	0x78, 0xd3, 0xfc, 0x0e, 0x66, 0x5e, 0x6a, 0xd5, 0x93, 0x98, 0x58, 0x0d, 0x0e, 0x6d, 0x55, 0x4f,
	0x7c, 0x01, 0x71, 0x5b, 0x50, 0x43, 0x43, 0x8d, 0x22, 0x48, 0x59, 0x3e, 0x91, 0xc7, 0x9a, 0xdf,
	0x02, 0xb4, 0xaa, 0xdb, 0x7b, 0x7b, 0x66, 0xed, 0x09, 0xc9, 0xee, 0x61, 0x3e, 0xb6, 0x62, 0xb4,
	0xea, 0x0c, 0x72, 0x01, 0x91, 0x19, 0xaa, 0x0a, 0x8d, 0xb1, 0x9d, 0xc4, 0x72, 0x2c, 0xb3, 0x1f,
	0x06, 0xd1, 0x46, 0xbe, 0x76, 0xd4, 0x7f, 0xfd, 0x5f, 0xc7, 0xfc, 0x06, 0xa0, 0xea, 0xb1, 0x20,
	0xac, 0x77, 0x05, 0x89, 0x69, 0xca, 0xf2, 0x40, 0x26, 0x9e, 0xac, 0xe9, 0xa0, 0x07, 0x5d, 0x8f,
	0x3a, 0x74, 0xda, 0x93, 0x35, 0x65, 0x8f, 0x90, 0xb8, 0x11, 0x1a, 0x34, 0x3c, 0x87, 0x08, 0xdd,
	0x55, 0xb0, 0x34, 0xc8, 0x67, 0xab, 0xb9, 0x0b, 0x6a, 0xe9, 0xa7, 0x94, 0xa3, 0x5e, 0x3d, 0x43,
	0xf8, 0x61, 0x93, 0xe4, 0x4f, 0x87, 0x0f, 0xec, 0xc2, 0xb6, 0x2f, 0xfc, 0xf2, 0xf8, 0xfe, 0x24,
	0xcd, 0xc5, 0xd5, 0x1f, 0xea, 0x16, 0x5b, 0x86, 0x96, 0x3e, 0xfc, 0x06, 0x00, 0x00, 0xff, 0xff,
	0xea, 0xd9, 0xf4, 0x1d, 0x14, 0x02, 0x00, 0x00,
}
