// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entry.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PeerEntry struct {
	PeerId               []byte   `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	LocalIp              string   `protobuf:"bytes,2,opt,name=local_ip,json=localIp" json:"local_ip,omitempty"`
	LocalPort            string   `protobuf:"bytes,3,opt,name=local_port,json=localPort" json:"local_port,omitempty"`
	Latitude             float32  `protobuf:"fixed32,4,opt,name=latitude" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,5,opt,name=longitude" json:"longitude,omitempty"`
	IsRemote             bool     `protobuf:"varint,6,opt,name=is_remote,json=isRemote" json:"is_remote,omitempty"`
	Protocol             string   `protobuf:"bytes,7,opt,name=protocol" json:"protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerEntry) Reset()         { *m = PeerEntry{} }
func (m *PeerEntry) String() string { return proto.CompactTextString(m) }
func (*PeerEntry) ProtoMessage()    {}
func (*PeerEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_entry_bb195433b90c0dc9, []int{0}
}
func (m *PeerEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerEntry.Unmarshal(m, b)
}
func (m *PeerEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerEntry.Marshal(b, m, deterministic)
}
func (dst *PeerEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerEntry.Merge(dst, src)
}
func (m *PeerEntry) XXX_Size() int {
	return xxx_messageInfo_PeerEntry.Size(m)
}
func (m *PeerEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PeerEntry proto.InternalMessageInfo

func (m *PeerEntry) GetPeerId() []byte {
	if m != nil {
		return m.PeerId
	}
	return nil
}

func (m *PeerEntry) GetLocalIp() string {
	if m != nil {
		return m.LocalIp
	}
	return ""
}

func (m *PeerEntry) GetLocalPort() string {
	if m != nil {
		return m.LocalPort
	}
	return ""
}

func (m *PeerEntry) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *PeerEntry) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *PeerEntry) GetIsRemote() bool {
	if m != nil {
		return m.IsRemote
	}
	return false
}

func (m *PeerEntry) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

type ProxyEntry struct {
	Id                   uint32   `protobuf:"varint,7,opt,name=id" json:"id,omitempty"`
	UniqueKey            string   `protobuf:"bytes,8,opt,name=unique_key,json=uniqueKey" json:"unique_key,omitempty"`
	GlobalIp             string   `protobuf:"bytes,1,opt,name=global_ip,json=globalIp" json:"global_ip,omitempty"`
	GlobalPort           string   `protobuf:"bytes,2,opt,name=global_port,json=globalPort" json:"global_port,omitempty"`
	Latitude             float32  `protobuf:"fixed32,3,opt,name=latitude" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,4,opt,name=longitude" json:"longitude,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,6,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyEntry) Reset()         { *m = ProxyEntry{} }
func (m *ProxyEntry) String() string { return proto.CompactTextString(m) }
func (*ProxyEntry) ProtoMessage()    {}
func (*ProxyEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_entry_bb195433b90c0dc9, []int{1}
}
func (m *ProxyEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyEntry.Unmarshal(m, b)
}
func (m *ProxyEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyEntry.Marshal(b, m, deterministic)
}
func (dst *ProxyEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyEntry.Merge(dst, src)
}
func (m *ProxyEntry) XXX_Size() int {
	return xxx_messageInfo_ProxyEntry.Size(m)
}
func (m *ProxyEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyEntry proto.InternalMessageInfo

func (m *ProxyEntry) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProxyEntry) GetUniqueKey() string {
	if m != nil {
		return m.UniqueKey
	}
	return ""
}

func (m *ProxyEntry) GetGlobalIp() string {
	if m != nil {
		return m.GlobalIp
	}
	return ""
}

func (m *ProxyEntry) GetGlobalPort() string {
	if m != nil {
		return m.GlobalPort
	}
	return ""
}

func (m *ProxyEntry) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *ProxyEntry) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *ProxyEntry) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *ProxyEntry) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*PeerEntry)(nil), "proto.PeerEntry")
	proto.RegisterType((*ProxyEntry)(nil), "proto.ProxyEntry")
}

func init() { proto.RegisterFile("entry.proto", fileDescriptor_entry_bb195433b90c0dc9) }

var fileDescriptor_entry_bb195433b90c0dc9 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x4d, 0x4e, 0xf3, 0x30,
	0x10, 0x86, 0xe5, 0xb4, 0x4d, 0xe3, 0xe9, 0xf7, 0xb1, 0xf0, 0x06, 0xf3, 0x53, 0x11, 0x75, 0x95,
	0x15, 0x1b, 0x4e, 0xd0, 0x05, 0x8b, 0x8a, 0x4d, 0xe5, 0x0b, 0x44, 0x69, 0x3c, 0xaa, 0x2c, 0x4c,
	0x6c, 0x5c, 0x47, 0x22, 0xc7, 0xe4, 0x28, 0xdc, 0x00, 0x65, 0x1c, 0x8a, 0x04, 0x12, 0xab, 0xe8,
	0x7d, 0x9f, 0xc8, 0x33, 0xcf, 0xc0, 0x0a, 0xbb, 0x18, 0x86, 0x7b, 0x1f, 0x5c, 0x74, 0x62, 0x41,
	0x9f, 0xcd, 0x3b, 0x03, 0xbe, 0x47, 0x0c, 0x8f, 0x23, 0x12, 0x97, 0xb0, 0xf4, 0x88, 0xa1, 0x36,
	0x5a, 0xb2, 0x92, 0x55, 0xff, 0x54, 0x3e, 0xc6, 0x9d, 0x16, 0x57, 0x50, 0x58, 0xd7, 0x36, 0xb6,
	0x36, 0x5e, 0x66, 0x25, 0xab, 0xb8, 0x5a, 0x52, 0xde, 0x79, 0xb1, 0x06, 0x48, 0xc8, 0xbb, 0x10,
	0xe5, 0x8c, 0x20, 0xa7, 0x66, 0xef, 0x42, 0x14, 0xd7, 0x50, 0xd8, 0x26, 0x9a, 0xd8, 0x6b, 0x94,
	0xf3, 0x92, 0x55, 0x99, 0x3a, 0x67, 0x71, 0x0b, 0xdc, 0xba, 0xee, 0x98, 0xe0, 0x82, 0xe0, 0x77,
	0x21, 0x6e, 0x80, 0x9b, 0x53, 0x1d, 0xf0, 0xc5, 0x45, 0x94, 0x79, 0xc9, 0xaa, 0x42, 0x15, 0xe6,
	0xa4, 0x28, 0x8f, 0xcf, 0x92, 0x40, 0xeb, 0xac, 0x5c, 0xd2, 0xcc, 0x73, 0xde, 0x7c, 0x30, 0x80,
	0x7d, 0x70, 0x6f, 0x43, 0x92, 0xba, 0x80, 0xcc, 0x68, 0xfa, 0xe9, 0xbf, 0xca, 0x8c, 0x1e, 0x17,
	0xee, 0x3b, 0xf3, 0xda, 0x63, 0xfd, 0x8c, 0x83, 0x2c, 0xd2, 0xc2, 0xa9, 0x79, 0xc2, 0x61, 0x1c,
	0x7b, 0xb4, 0xee, 0x90, 0x5c, 0x59, 0x7a, 0x3a, 0x15, 0x3b, 0x2f, 0xee, 0x60, 0x35, 0x41, 0xb2,
	0x4d, 0xa7, 0x80, 0x54, 0xfd, 0xd2, 0x9d, 0xfd, 0xa5, 0x3b, 0xff, 0xa9, 0xbb, 0x06, 0x68, 0x03,
	0x36, 0x11, 0x75, 0xdd, 0x44, 0xba, 0xc6, 0x4c, 0xf1, 0xa9, 0xd9, 0x46, 0xda, 0xda, 0xeb, 0x2f,
	0x9c, 0x27, 0x3c, 0x35, 0xdb, 0x78, 0xc8, 0xc9, 0xfe, 0xe1, 0x33, 0x00, 0x00, 0xff, 0xff, 0x54,
	0xd8, 0xce, 0x22, 0xe4, 0x01, 0x00, 0x00,
}
