// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entry.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PeerEntry struct {
	PeerId               string   `protobuf:"bytes,1,opt,name=peer_id,json=peerId" json:"peer_id,omitempty"`
	ProxyIp              string   `protobuf:"bytes,2,opt,name=proxy_ip,json=proxyIp" json:"proxy_ip,omitempty"`
	Latitude             float32  `protobuf:"fixed32,4,opt,name=latitude" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,5,opt,name=longitude" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerEntry) Reset()         { *m = PeerEntry{} }
func (m *PeerEntry) String() string { return proto.CompactTextString(m) }
func (*PeerEntry) ProtoMessage()    {}
func (*PeerEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_entry_ceb531a85f120abb, []int{0}
}
func (m *PeerEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerEntry.Unmarshal(m, b)
}
func (m *PeerEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerEntry.Marshal(b, m, deterministic)
}
func (dst *PeerEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerEntry.Merge(dst, src)
}
func (m *PeerEntry) XXX_Size() int {
	return xxx_messageInfo_PeerEntry.Size(m)
}
func (m *PeerEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PeerEntry proto.InternalMessageInfo

func (m *PeerEntry) GetPeerId() string {
	if m != nil {
		return m.PeerId
	}
	return ""
}

func (m *PeerEntry) GetProxyIp() string {
	if m != nil {
		return m.ProxyIp
	}
	return ""
}

func (m *PeerEntry) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *PeerEntry) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type ProxyEntry struct {
	Id                   uint32   `protobuf:"varint,7,opt,name=id" json:"id,omitempty"`
	UniqueKey            string   `protobuf:"bytes,8,opt,name=unique_key,json=uniqueKey" json:"unique_key,omitempty"`
	GlobalIp             string   `protobuf:"bytes,1,opt,name=global_ip,json=globalIp" json:"global_ip,omitempty"`
	GlobalPort           string   `protobuf:"bytes,2,opt,name=global_port,json=globalPort" json:"global_port,omitempty"`
	Latitude             float32  `protobuf:"fixed32,3,opt,name=latitude" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,4,opt,name=longitude" json:"longitude,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,6,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyEntry) Reset()         { *m = ProxyEntry{} }
func (m *ProxyEntry) String() string { return proto.CompactTextString(m) }
func (*ProxyEntry) ProtoMessage()    {}
func (*ProxyEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_entry_ceb531a85f120abb, []int{1}
}
func (m *ProxyEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyEntry.Unmarshal(m, b)
}
func (m *ProxyEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyEntry.Marshal(b, m, deterministic)
}
func (dst *ProxyEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyEntry.Merge(dst, src)
}
func (m *ProxyEntry) XXX_Size() int {
	return xxx_messageInfo_ProxyEntry.Size(m)
}
func (m *ProxyEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyEntry.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyEntry proto.InternalMessageInfo

func (m *ProxyEntry) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProxyEntry) GetUniqueKey() string {
	if m != nil {
		return m.UniqueKey
	}
	return ""
}

func (m *ProxyEntry) GetGlobalIp() string {
	if m != nil {
		return m.GlobalIp
	}
	return ""
}

func (m *ProxyEntry) GetGlobalPort() string {
	if m != nil {
		return m.GlobalPort
	}
	return ""
}

func (m *ProxyEntry) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *ProxyEntry) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *ProxyEntry) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *ProxyEntry) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*PeerEntry)(nil), "proto.PeerEntry")
	proto.RegisterType((*ProxyEntry)(nil), "proto.ProxyEntry")
}

func init() { proto.RegisterFile("entry.proto", fileDescriptor_entry_ceb531a85f120abb) }

var fileDescriptor_entry_ceb531a85f120abb = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0x80, 0x49, 0x77, 0xb7, 0x6d, 0x66, 0xd1, 0x43, 0x2e, 0xc6, 0x3f, 0x2c, 0x7b, 0xea, 0xc9,
	0x8b, 0x4f, 0xb0, 0x07, 0x0f, 0xc5, 0x4b, 0xe9, 0x0b, 0x94, 0xae, 0x19, 0x4a, 0xb0, 0x34, 0x31,
	0x4c, 0xc1, 0x3c, 0xb6, 0x6f, 0x20, 0x49, 0xaa, 0xa2, 0x87, 0x3d, 0x85, 0xf9, 0x3e, 0xc8, 0x7c,
	0x09, 0xec, 0x71, 0x26, 0xe7, 0x1f, 0xad, 0x33, 0x64, 0xc4, 0x2e, 0x1e, 0x07, 0x0f, 0xbc, 0x45,
	0x74, 0xcf, 0xc1, 0x88, 0x2b, 0x28, 0x2c, 0xa2, 0xeb, 0xb5, 0x92, 0xac, 0x62, 0x35, 0xef, 0xf2,
	0x30, 0x36, 0x4a, 0x5c, 0x43, 0x69, 0x9d, 0xf9, 0xf0, 0xbd, 0xb6, 0x32, 0x8b, 0xa6, 0x88, 0x73,
	0x63, 0xc5, 0x0d, 0x94, 0xd3, 0x40, 0x9a, 0x16, 0x85, 0x72, 0x5b, 0xb1, 0x3a, 0xeb, 0x7e, 0x66,
	0x71, 0x07, 0x7c, 0x32, 0xf3, 0x98, 0xe4, 0x2e, 0xca, 0x5f, 0x70, 0xf8, 0x64, 0x00, 0x6d, 0xb8,
	0x25, 0x2d, 0xbf, 0x84, 0x4c, 0x2b, 0x59, 0x54, 0xac, 0xbe, 0xe8, 0x32, 0xad, 0xc4, 0x3d, 0xc0,
	0x32, 0xeb, 0xf7, 0x05, 0xfb, 0x37, 0xf4, 0xb2, 0x8c, 0x5b, 0x79, 0x22, 0x2f, 0xe8, 0xc5, 0x2d,
	0xf0, 0x71, 0x32, 0xa7, 0x61, 0x0a, 0x4d, 0xa9, 0xb6, 0x4c, 0xa0, 0xb1, 0xe2, 0x01, 0xf6, 0xab,
	0xb4, 0xc6, 0xd1, 0x9a, 0x0c, 0x09, 0xb5, 0xc6, 0xd1, 0x9f, 0xea, 0xcd, 0xb9, 0xea, 0xed, 0xbf,
	0xea, 0x90, 0xf5, 0xea, 0x70, 0x20, 0x54, 0xfd, 0x40, 0xf1, 0x51, 0x9b, 0x8e, 0xaf, 0xe4, 0x48,
	0xb1, 0xda, 0xaa, 0x6f, 0x9d, 0x27, 0xbd, 0x92, 0x23, 0x9d, 0xf2, 0xf8, 0xeb, 0x4f, 0x5f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x02, 0x1b, 0x67, 0x24, 0x8b, 0x01, 0x00, 0x00,
}
