// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lr.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PeerJoinRequest struct {
	PeerId               []byte   `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	LocalIp              string   `protobuf:"bytes,2,opt,name=local_ip,json=localIp" json:"local_ip,omitempty"`
	LocalPort            string   `protobuf:"bytes,3,opt,name=local_port,json=localPort" json:"local_port,omitempty"`
	Latitude             float32  `protobuf:"fixed32,4,opt,name=latitude" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,5,opt,name=longitude" json:"longitude,omitempty"`
	Protocol             string   `protobuf:"bytes,6,opt,name=protocol" json:"protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerJoinRequest) Reset()         { *m = PeerJoinRequest{} }
func (m *PeerJoinRequest) String() string { return proto.CompactTextString(m) }
func (*PeerJoinRequest) ProtoMessage()    {}
func (*PeerJoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lr_ad94bca602fc03b7, []int{0}
}
func (m *PeerJoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerJoinRequest.Unmarshal(m, b)
}
func (m *PeerJoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerJoinRequest.Marshal(b, m, deterministic)
}
func (dst *PeerJoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerJoinRequest.Merge(dst, src)
}
func (m *PeerJoinRequest) XXX_Size() int {
	return xxx_messageInfo_PeerJoinRequest.Size(m)
}
func (m *PeerJoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerJoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PeerJoinRequest proto.InternalMessageInfo

func (m *PeerJoinRequest) GetPeerId() []byte {
	if m != nil {
		return m.PeerId
	}
	return nil
}

func (m *PeerJoinRequest) GetLocalIp() string {
	if m != nil {
		return m.LocalIp
	}
	return ""
}

func (m *PeerJoinRequest) GetLocalPort() string {
	if m != nil {
		return m.LocalPort
	}
	return ""
}

func (m *PeerJoinRequest) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *PeerJoinRequest) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *PeerJoinRequest) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

type PeerJoinResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerJoinResponse) Reset()         { *m = PeerJoinResponse{} }
func (m *PeerJoinResponse) String() string { return proto.CompactTextString(m) }
func (*PeerJoinResponse) ProtoMessage()    {}
func (*PeerJoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_lr_ad94bca602fc03b7, []int{1}
}
func (m *PeerJoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerJoinResponse.Unmarshal(m, b)
}
func (m *PeerJoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerJoinResponse.Marshal(b, m, deterministic)
}
func (dst *PeerJoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerJoinResponse.Merge(dst, src)
}
func (m *PeerJoinResponse) XXX_Size() int {
	return xxx_messageInfo_PeerJoinResponse.Size(m)
}
func (m *PeerJoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerJoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PeerJoinResponse proto.InternalMessageInfo

func (m *PeerJoinResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ExchangeEntriesNotification struct {
	Destinations         []*ProxyEntry `protobuf:"bytes,1,rep,name=destinations" json:"destinations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ExchangeEntriesNotification) Reset()         { *m = ExchangeEntriesNotification{} }
func (m *ExchangeEntriesNotification) String() string { return proto.CompactTextString(m) }
func (*ExchangeEntriesNotification) ProtoMessage()    {}
func (*ExchangeEntriesNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_lr_ad94bca602fc03b7, []int{2}
}
func (m *ExchangeEntriesNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeEntriesNotification.Unmarshal(m, b)
}
func (m *ExchangeEntriesNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeEntriesNotification.Marshal(b, m, deterministic)
}
func (dst *ExchangeEntriesNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeEntriesNotification.Merge(dst, src)
}
func (m *ExchangeEntriesNotification) XXX_Size() int {
	return xxx_messageInfo_ExchangeEntriesNotification.Size(m)
}
func (m *ExchangeEntriesNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeEntriesNotification.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeEntriesNotification proto.InternalMessageInfo

func (m *ExchangeEntriesNotification) GetDestinations() []*ProxyEntry {
	if m != nil {
		return m.Destinations
	}
	return nil
}

type ExchangeEntriesRequest struct {
	Entries              []*PeerEntry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ExchangeEntriesRequest) Reset()         { *m = ExchangeEntriesRequest{} }
func (m *ExchangeEntriesRequest) String() string { return proto.CompactTextString(m) }
func (*ExchangeEntriesRequest) ProtoMessage()    {}
func (*ExchangeEntriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lr_ad94bca602fc03b7, []int{3}
}
func (m *ExchangeEntriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeEntriesRequest.Unmarshal(m, b)
}
func (m *ExchangeEntriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeEntriesRequest.Marshal(b, m, deterministic)
}
func (dst *ExchangeEntriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeEntriesRequest.Merge(dst, src)
}
func (m *ExchangeEntriesRequest) XXX_Size() int {
	return xxx_messageInfo_ExchangeEntriesRequest.Size(m)
}
func (m *ExchangeEntriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeEntriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeEntriesRequest proto.InternalMessageInfo

func (m *ExchangeEntriesRequest) GetEntries() []*PeerEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type ExchangeEntriesResponse struct {
	Entries              []*PeerEntry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ExchangeEntriesResponse) Reset()         { *m = ExchangeEntriesResponse{} }
func (m *ExchangeEntriesResponse) String() string { return proto.CompactTextString(m) }
func (*ExchangeEntriesResponse) ProtoMessage()    {}
func (*ExchangeEntriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_lr_ad94bca602fc03b7, []int{4}
}
func (m *ExchangeEntriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExchangeEntriesResponse.Unmarshal(m, b)
}
func (m *ExchangeEntriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExchangeEntriesResponse.Marshal(b, m, deterministic)
}
func (dst *ExchangeEntriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExchangeEntriesResponse.Merge(dst, src)
}
func (m *ExchangeEntriesResponse) XXX_Size() int {
	return xxx_messageInfo_ExchangeEntriesResponse.Size(m)
}
func (m *ExchangeEntriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExchangeEntriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExchangeEntriesResponse proto.InternalMessageInfo

func (m *ExchangeEntriesResponse) GetEntries() []*PeerEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func init() {
	proto.RegisterType((*PeerJoinRequest)(nil), "proto.PeerJoinRequest")
	proto.RegisterType((*PeerJoinResponse)(nil), "proto.PeerJoinResponse")
	proto.RegisterType((*ExchangeEntriesNotification)(nil), "proto.ExchangeEntriesNotification")
	proto.RegisterType((*ExchangeEntriesRequest)(nil), "proto.ExchangeEntriesRequest")
	proto.RegisterType((*ExchangeEntriesResponse)(nil), "proto.ExchangeEntriesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProxyClient is the client API for Proxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProxyClient interface {
	Heartbeat(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	ExchangeEntriesStubRPC(ctx context.Context, in *ExchangeEntriesNotification, opts ...grpc.CallOption) (*Empty, error)
	ExchangeEntriesDriverRPC(ctx context.Context, in *ExchangeEntriesRequest, opts ...grpc.CallOption) (*ExchangeEntriesResponse, error)
	LookUpPeersRPC(ctx context.Context, in *LookUpPeerRequest, opts ...grpc.CallOption) (*LookUpPeerResponse, error)
	FetchPeersRPC(ctx context.Context, in *FetchPeersRequest, opts ...grpc.CallOption) (*FetchPeersResponse, error)
}

type proxyClient struct {
	cc *grpc.ClientConn
}

func NewProxyClient(cc *grpc.ClientConn) ProxyClient {
	return &proxyClient{cc}
}

func (c *proxyClient) Heartbeat(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Proxy/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) ExchangeEntriesStubRPC(ctx context.Context, in *ExchangeEntriesNotification, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Proxy/ExchangeEntriesStubRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) ExchangeEntriesDriverRPC(ctx context.Context, in *ExchangeEntriesRequest, opts ...grpc.CallOption) (*ExchangeEntriesResponse, error) {
	out := new(ExchangeEntriesResponse)
	err := c.cc.Invoke(ctx, "/proto.Proxy/ExchangeEntriesDriverRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) LookUpPeersRPC(ctx context.Context, in *LookUpPeerRequest, opts ...grpc.CallOption) (*LookUpPeerResponse, error) {
	out := new(LookUpPeerResponse)
	err := c.cc.Invoke(ctx, "/proto.Proxy/LookUpPeersRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) FetchPeersRPC(ctx context.Context, in *FetchPeersRequest, opts ...grpc.CallOption) (*FetchPeersResponse, error) {
	out := new(FetchPeersResponse)
	err := c.cc.Invoke(ctx, "/proto.Proxy/FetchPeersRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Proxy service

type ProxyServer interface {
	Heartbeat(context.Context, *Empty) (*Empty, error)
	ExchangeEntriesStubRPC(context.Context, *ExchangeEntriesNotification) (*Empty, error)
	ExchangeEntriesDriverRPC(context.Context, *ExchangeEntriesRequest) (*ExchangeEntriesResponse, error)
	LookUpPeersRPC(context.Context, *LookUpPeerRequest) (*LookUpPeerResponse, error)
	FetchPeersRPC(context.Context, *FetchPeersRequest) (*FetchPeersResponse, error)
}

func RegisterProxyServer(s *grpc.Server, srv ProxyServer) {
	s.RegisterService(&_Proxy_serviceDesc, srv)
}

func _Proxy_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Proxy/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).Heartbeat(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_ExchangeEntriesStubRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeEntriesNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).ExchangeEntriesStubRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Proxy/ExchangeEntriesStubRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).ExchangeEntriesStubRPC(ctx, req.(*ExchangeEntriesNotification))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_ExchangeEntriesDriverRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).ExchangeEntriesDriverRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Proxy/ExchangeEntriesDriverRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).ExchangeEntriesDriverRPC(ctx, req.(*ExchangeEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_LookUpPeersRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookUpPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).LookUpPeersRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Proxy/LookUpPeersRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).LookUpPeersRPC(ctx, req.(*LookUpPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_FetchPeersRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).FetchPeersRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Proxy/FetchPeersRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).FetchPeersRPC(ctx, req.(*FetchPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Proxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Proxy",
	HandlerType: (*ProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _Proxy_Heartbeat_Handler,
		},
		{
			MethodName: "ExchangeEntriesStubRPC",
			Handler:    _Proxy_ExchangeEntriesStubRPC_Handler,
		},
		{
			MethodName: "ExchangeEntriesDriverRPC",
			Handler:    _Proxy_ExchangeEntriesDriverRPC_Handler,
		},
		{
			MethodName: "LookUpPeersRPC",
			Handler:    _Proxy_LookUpPeersRPC_Handler,
		},
		{
			MethodName: "FetchPeersRPC",
			Handler:    _Proxy_FetchPeersRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lr.proto",
}

func init() { proto.RegisterFile("lr.proto", fileDescriptor_lr_ad94bca602fc03b7) }

var fileDescriptor_lr_ad94bca602fc03b7 = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x6e, 0x13, 0x31,
	0x10, 0x87, 0xb5, 0x29, 0xf9, 0x37, 0x4d, 0xa1, 0xf8, 0x40, 0xdd, 0x40, 0x51, 0xb4, 0x17, 0x22,
	0x84, 0x72, 0x28, 0xe2, 0x09, 0xc8, 0x22, 0x5a, 0x21, 0x14, 0x2d, 0x70, 0xe0, 0x54, 0x6d, 0x36,
	0x43, 0x6b, 0xb1, 0xd8, 0xc6, 0x9e, 0x45, 0xcd, 0xab, 0xf1, 0x3c, 0x3c, 0x08, 0xb2, 0xbd, 0x6e,
	0xda, 0x4d, 0x73, 0xe8, 0x69, 0xf5, 0xcd, 0x6f, 0xe6, 0xd3, 0x78, 0xb4, 0x30, 0xa8, 0xcc, 0x4c,
	0x1b, 0x45, 0x8a, 0x75, 0xfd, 0x67, 0xbc, 0x8f, 0xbf, 0x34, 0xad, 0x67, 0x11, 0x24, 0x99, 0x08,
	0x07, 0x06, 0x7f, 0xd7, 0x68, 0x29, 0x60, 0xfa, 0x37, 0x81, 0x27, 0x0b, 0x44, 0x73, 0xae, 0x84,
	0xcc, 0x43, 0xc2, 0x8e, 0xa0, 0xaf, 0x11, 0xcd, 0x85, 0x58, 0xf1, 0x64, 0x92, 0x4c, 0x47, 0x79,
	0xcf, 0xe1, 0xd9, 0x8a, 0x1d, 0xc3, 0xa0, 0x52, 0x65, 0x51, 0x5d, 0x08, 0xcd, 0x3b, 0x93, 0x64,
	0x3a, 0xcc, 0xfb, 0x9e, 0xcf, 0x34, 0x3b, 0x01, 0x08, 0x91, 0x56, 0x86, 0xf8, 0x9e, 0x0f, 0x87,
	0xbe, 0xb2, 0x50, 0x86, 0xd8, 0x18, 0x06, 0x55, 0x41, 0x82, 0xea, 0x15, 0xf2, 0x47, 0x93, 0x64,
	0xda, 0xc9, 0x6f, 0x98, 0xbd, 0x80, 0x61, 0xa5, 0xe4, 0x65, 0x08, 0xbb, 0x3e, 0xdc, 0x14, 0xdc,
	0xa4, 0xdf, 0xb4, 0x54, 0x15, 0xef, 0x79, 0xed, 0x0d, 0xa7, 0x6f, 0xe0, 0x70, 0xb3, 0xbb, 0xd5,
	0x4a, 0x5a, 0x64, 0x1c, 0xfa, 0xb6, 0x2e, 0x4b, 0xb4, 0xd6, 0x2f, 0x3f, 0xc8, 0x23, 0xa6, 0x5f,
	0xe1, 0x79, 0x76, 0x5d, 0x5e, 0x15, 0xf2, 0x12, 0x33, 0x49, 0x46, 0xa0, 0xfd, 0xac, 0x48, 0xfc,
	0x10, 0x65, 0x41, 0x42, 0x49, 0xf6, 0x0e, 0x46, 0x2b, 0xb4, 0x24, 0xa4, 0x47, 0x37, 0xbd, 0x37,
	0xdd, 0x3f, 0x7d, 0x1a, 0xee, 0x34, 0x5b, 0x18, 0x75, 0xbd, 0x76, 0x63, 0xeb, 0xfc, 0x4e, 0x5b,
	0x3a, 0x87, 0x67, 0x2d, 0x6b, 0x3c, 0xe3, 0x6b, 0xe8, 0x63, 0xa8, 0x34, 0xae, 0xc3, 0xe8, 0x42,
	0x34, 0x41, 0x15, 0x1b, 0xd2, 0x0c, 0x8e, 0xb6, 0x2c, 0xcd, 0x83, 0x1e, 0xa0, 0x39, 0xfd, 0xd7,
	0x81, 0xae, 0xdf, 0x94, 0xbd, 0x82, 0xe1, 0x47, 0x2c, 0x0c, 0x2d, 0xb1, 0x20, 0x36, 0x6a, 0x26,
	0x32, 0xf7, 0x53, 0x8c, 0xef, 0x10, 0x3b, 0xdf, 0xda, 0xff, 0x0b, 0xd5, 0xcb, 0x7c, 0xf1, 0x9e,
	0xa5, 0xb1, 0x6f, 0xf7, 0xd1, 0x5a, 0xae, 0xef, 0xc0, 0x5b, 0xcd, 0x73, 0x23, 0xfe, 0xa0, 0x71,
	0xb6, 0x93, 0xfb, 0x6d, 0xcd, 0xb1, 0xc6, 0x2f, 0x77, 0xc5, 0xcd, 0x15, 0x32, 0x78, 0xfc, 0x49,
	0xa9, 0x9f, 0xdf, 0xb4, 0x7b, 0xb5, 0x75, 0x42, 0xde, 0x4c, 0x6c, 0xca, 0xd1, 0x75, 0x7c, 0x4f,
	0xd2, 0x68, 0xe6, 0x70, 0xf0, 0x01, 0xa9, 0xbc, 0xda, 0xb2, 0xdc, 0xaa, 0xb6, 0x2c, 0xb7, 0x93,
	0x60, 0x59, 0xf6, 0x7c, 0xf2, 0xf6, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x95, 0xfe, 0x2f, 0xe0,
	0x77, 0x03, 0x00, 0x00,
}
