// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tablet.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProxyJoinRequest struct {
	UniqueKey            string   `protobuf:"bytes,1,opt,name=unique_key,json=uniqueKey" json:"unique_key,omitempty"`
	GlobalPort           string   `protobuf:"bytes,2,opt,name=global_port,json=globalPort" json:"global_port,omitempty"`
	Latitude             float32  `protobuf:"fixed32,3,opt,name=latitude" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,4,opt,name=longitude" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyJoinRequest) Reset()         { *m = ProxyJoinRequest{} }
func (m *ProxyJoinRequest) String() string { return proto.CompactTextString(m) }
func (*ProxyJoinRequest) ProtoMessage()    {}
func (*ProxyJoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tablet_d78a643894e1a960, []int{0}
}
func (m *ProxyJoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyJoinRequest.Unmarshal(m, b)
}
func (m *ProxyJoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyJoinRequest.Marshal(b, m, deterministic)
}
func (dst *ProxyJoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyJoinRequest.Merge(dst, src)
}
func (m *ProxyJoinRequest) XXX_Size() int {
	return xxx_messageInfo_ProxyJoinRequest.Size(m)
}
func (m *ProxyJoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyJoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyJoinRequest proto.InternalMessageInfo

func (m *ProxyJoinRequest) GetUniqueKey() string {
	if m != nil {
		return m.UniqueKey
	}
	return ""
}

func (m *ProxyJoinRequest) GetGlobalPort() string {
	if m != nil {
		return m.GlobalPort
	}
	return ""
}

func (m *ProxyJoinRequest) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *ProxyJoinRequest) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type LookUpRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookUpRequest) Reset()         { *m = LookUpRequest{} }
func (m *LookUpRequest) String() string { return proto.CompactTextString(m) }
func (*LookUpRequest) ProtoMessage()    {}
func (*LookUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_tablet_d78a643894e1a960, []int{1}
}
func (m *LookUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookUpRequest.Unmarshal(m, b)
}
func (m *LookUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookUpRequest.Marshal(b, m, deterministic)
}
func (dst *LookUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookUpRequest.Merge(dst, src)
}
func (m *LookUpRequest) XXX_Size() int {
	return xxx_messageInfo_LookUpRequest.Size(m)
}
func (m *LookUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookUpRequest proto.InternalMessageInfo

func (m *LookUpRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ProxyEntries struct {
	Entries              []*ProxyEntry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ProxyEntries) Reset()         { *m = ProxyEntries{} }
func (m *ProxyEntries) String() string { return proto.CompactTextString(m) }
func (*ProxyEntries) ProtoMessage()    {}
func (*ProxyEntries) Descriptor() ([]byte, []int) {
	return fileDescriptor_tablet_d78a643894e1a960, []int{2}
}
func (m *ProxyEntries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyEntries.Unmarshal(m, b)
}
func (m *ProxyEntries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyEntries.Marshal(b, m, deterministic)
}
func (dst *ProxyEntries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyEntries.Merge(dst, src)
}
func (m *ProxyEntries) XXX_Size() int {
	return xxx_messageInfo_ProxyEntries.Size(m)
}
func (m *ProxyEntries) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyEntries.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyEntries proto.InternalMessageInfo

func (m *ProxyEntries) GetEntries() []*ProxyEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func init() {
	proto.RegisterType((*ProxyJoinRequest)(nil), "proto.ProxyJoinRequest")
	proto.RegisterType((*LookUpRequest)(nil), "proto.LookUpRequest")
	proto.RegisterType((*ProxyEntries)(nil), "proto.ProxyEntries")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TabletClient is the client API for Tablet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TabletClient interface {
	ProxyJoinRPC(ctx context.Context, in *ProxyJoinRequest, opts ...grpc.CallOption) (*ProxyEntry, error)
	LookUpRPC(ctx context.Context, in *LookUpRequest, opts ...grpc.CallOption) (*ProxyEntry, error)
	LookUpPeersRPC(ctx context.Context, in *LookUpPeerRequest, opts ...grpc.CallOption) (*LookUpPeerResponse, error)
}

type tabletClient struct {
	cc *grpc.ClientConn
}

func NewTabletClient(cc *grpc.ClientConn) TabletClient {
	return &tabletClient{cc}
}

func (c *tabletClient) ProxyJoinRPC(ctx context.Context, in *ProxyJoinRequest, opts ...grpc.CallOption) (*ProxyEntry, error) {
	out := new(ProxyEntry)
	err := c.cc.Invoke(ctx, "/proto.Tablet/ProxyJoinRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tabletClient) LookUpRPC(ctx context.Context, in *LookUpRequest, opts ...grpc.CallOption) (*ProxyEntry, error) {
	out := new(ProxyEntry)
	err := c.cc.Invoke(ctx, "/proto.Tablet/LookUpRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tabletClient) LookUpPeersRPC(ctx context.Context, in *LookUpPeerRequest, opts ...grpc.CallOption) (*LookUpPeerResponse, error) {
	out := new(LookUpPeerResponse)
	err := c.cc.Invoke(ctx, "/proto.Tablet/LookUpPeersRPC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Tablet service

type TabletServer interface {
	ProxyJoinRPC(context.Context, *ProxyJoinRequest) (*ProxyEntry, error)
	LookUpRPC(context.Context, *LookUpRequest) (*ProxyEntry, error)
	LookUpPeersRPC(context.Context, *LookUpPeerRequest) (*LookUpPeerResponse, error)
}

func RegisterTabletServer(s *grpc.Server, srv TabletServer) {
	s.RegisterService(&_Tablet_serviceDesc, srv)
}

func _Tablet_ProxyJoinRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TabletServer).ProxyJoinRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Tablet/ProxyJoinRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TabletServer).ProxyJoinRPC(ctx, req.(*ProxyJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tablet_LookUpRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TabletServer).LookUpRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Tablet/LookUpRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TabletServer).LookUpRPC(ctx, req.(*LookUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tablet_LookUpPeersRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookUpPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TabletServer).LookUpPeersRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Tablet/LookUpPeersRPC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TabletServer).LookUpPeersRPC(ctx, req.(*LookUpPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tablet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Tablet",
	HandlerType: (*TabletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProxyJoinRPC",
			Handler:    _Tablet_ProxyJoinRPC_Handler,
		},
		{
			MethodName: "LookUpRPC",
			Handler:    _Tablet_LookUpRPC_Handler,
		},
		{
			MethodName: "LookUpPeersRPC",
			Handler:    _Tablet_LookUpPeersRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tablet.proto",
}

func init() { proto.RegisterFile("tablet.proto", fileDescriptor_tablet_d78a643894e1a960) }

var fileDescriptor_tablet_d78a643894e1a960 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xd9, 0xf4, 0xff, 0xaf, 0x66, 0xda, 0x14, 0x5d, 0x04, 0x63, 0x50, 0x1a, 0x72, 0x0a,
	0x08, 0x3d, 0x54, 0x4f, 0x7a, 0x2c, 0xbd, 0xa8, 0x87, 0x10, 0xf4, 0x5c, 0x12, 0x32, 0x94, 0xa5,
	0x61, 0x27, 0xdd, 0x6c, 0xc0, 0x7c, 0x07, 0xbf, 0x94, 0xdf, 0x4c, 0xba, 0x9b, 0xd4, 0x16, 0x7b,
	0x4a, 0xf6, 0xfd, 0xde, 0x1b, 0xde, 0x0c, 0x8c, 0x75, 0x96, 0x97, 0xa8, 0x67, 0x95, 0x22, 0x4d,
	0xfc, 0xbf, 0xf9, 0x04, 0x9e, 0xc2, 0x6d, 0x83, 0x75, 0xa7, 0x06, 0x23, 0x94, 0x5a, 0xb5, 0xf6,
	0x11, 0x7d, 0x31, 0xb8, 0x48, 0x14, 0x7d, 0xb6, 0x2f, 0x24, 0x64, 0x6a, 0x7d, 0xfc, 0x0e, 0xa0,
	0x91, 0x62, 0xdb, 0xe0, 0x6a, 0x83, 0xad, 0xcf, 0x42, 0x16, 0xbb, 0xa9, 0x6b, 0x95, 0x57, 0x6c,
	0xf9, 0x14, 0x46, 0xeb, 0x92, 0xf2, 0xac, 0x5c, 0x55, 0xa4, 0xb4, 0xef, 0x18, 0x0e, 0x56, 0x4a,
	0x48, 0x69, 0x1e, 0xc0, 0x79, 0x99, 0x69, 0xa1, 0x9b, 0x02, 0xfd, 0x41, 0xc8, 0x62, 0x27, 0xdd,
	0xbf, 0xf9, 0x2d, 0xb8, 0x25, 0xc9, 0xb5, 0x85, 0xff, 0x0c, 0xfc, 0x15, 0xa2, 0x29, 0x78, 0x6f,
	0x44, 0x9b, 0x8f, 0xaa, 0xaf, 0x32, 0x01, 0x47, 0x14, 0xa6, 0x82, 0x97, 0x3a, 0xa2, 0x88, 0x9e,
	0x61, 0x6c, 0xea, 0x2e, 0xa5, 0x56, 0x02, 0x6b, 0x7e, 0x0f, 0x67, 0x68, 0x7f, 0x7d, 0x16, 0x0e,
	0xe2, 0xd1, 0xfc, 0xd2, 0x2e, 0x36, 0xdb, 0xbb, 0xda, 0xb4, 0x77, 0xcc, 0xbf, 0x19, 0x0c, 0xdf,
	0xcd, 0x81, 0xf8, 0x53, 0x37, 0xc7, 0xac, 0x9d, 0x2c, 0xf8, 0xf5, 0x61, 0xec, 0xe0, 0x16, 0xc1,
	0xdf, 0x79, 0xfc, 0x11, 0xdc, 0xae, 0x64, 0xb2, 0xe0, 0x57, 0x1d, 0x3f, 0xaa, 0x7d, 0x2a, 0xb5,
	0x84, 0x89, 0xf5, 0x24, 0x88, 0xaa, 0xde, 0x45, 0xfd, 0xa3, 0xe8, 0x4e, 0xee, 0xe3, 0x37, 0x27,
	0x48, 0x5d, 0x91, 0xac, 0x31, 0x1f, 0x1a, 0xf2, 0xf0, 0x13, 0x00, 0x00, 0xff, 0xff, 0x97, 0x04,
	0xe9, 0x59, 0xea, 0x01, 0x00, 0x00,
}
